openapi: 3.0.3
info:
  title: Private Terraform Registry
  version: 0.0.1
paths:
  /.well-known/terraform.json:
    get:
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  modules.v1:
                    type: string
      x-amazon-apigateway-integration:
        type: mock
        httpMethod: GET
        requestTemplates:
          application/json: >-
            {"statusCode": 200}
        responses:
          200:
            statusCode: 200
            responseTemplates:
              application/json: >-
                {"modules.v1": "https://$context.domainName/terraform/modules/v1"}
  /terraform/modules/v1/{namespace}/{name}/{provider}/versions:
    get:
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  modules:
                    type: array
                    items:
                      type: object
                      properties:
                        versions:
                          type: array
                          items:
                            type: object
                            properties:
                              version:
                                type: string
        "404":
          description: ""
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS
        uri: arn:${AWS::Partition}:apigateway:${AWS::Region}:dynamodb:action/Query
        credentials: arn:${AWS::Partition}:iam::${AWS::AccountId}:role/DynamoDBAccess
        requestTemplates:
          application/json: |
            #set($allParams = $input.params())
            #set($namespace = $util.escapeJavaScript($allParams.path.namespace))
            #set($name = $util.escapeJavaScript($allParams.path.name))
            #set($provider = $util.escapeJavaScript($allParams.path.provider))
            {
              "TableName": "$stageVariables.registry_db",
              "KeyConditionExpression": "#k0 = :v0 AND begins_with(#k1, :v1)",
              "ScanIndexForward": false,
              "ExpressionAttributeNames": {
                "#k0": "pk",
                "#k1": "sk",
                "#data": "data",
                "#version": "version"
              },
              "ExpressionAttributeValues": {
                ":v0": {
                  "S": "NAMESPACE#${namespace}#NAME#${name}#PROVIDER#${provider}"
                },
                ":v1": {
                  "S": "VERSION#"
                }
              },
              "ProjectionExpression": "#data.#version"
            }
        responses:
          200:
            statusCode: 200
            responseTemplates:
              application/json: >-
                {"modules":[{"versions":[#foreach($item in $input.path('$.Items'))#if($item.data.M.version.S != ""){"version":"$item.data.M.version.S"}#if( $foreach.hasNext ),#{end}#{end}#{end}]}]}
          default:
            statusCode: 500

  /terraform/modules/v1/{namespace}/{name}/{provider}/{version}/download:
    get:
      responses:
        "204":
          description: ""
          headers:
            X-Terraform-Get:
              schema:
                type: string
        "404":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  errors:
                    type: array
                    items:
                      type: string

      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS
        uri: arn:${AWS::Partition}:apigateway:${AWS::Region}:dynamodb:action/GetItem
        credentials: arn:${AWS::Partition}:iam::${AWS::AccountId}:role/DynamoDBAccess
        requestTemplates:
          application/json: |
            #set($allParams = $input.params())
            #set($namespace = $util.escapeJavaScript($allParams.path.namespace))
            #set($name = $util.escapeJavaScript($allParams.path.name))
            #set($provider = $util.escapeJavaScript($allParams.path.provider))
            #set($version = $util.escapeJavaScript($allParams.path.version))
            {
              "TableName": "$stageVariables.registry_db",
              "Key": {
                "pk": {
                  "S": "NAMESPACE#${namespace}#NAME#${name}#PROVIDER#${provider}"
                },
                "sk": {
                  "S": "VERSION#${version}"
                }
              },
              "ProjectionExpression": "#data.#url",
              "ExpressionAttributeNames": {
                "#data": "data",
                "#url": "url"
              }
            }
        responses:
          200:
            statusCode: 204
            responseTemplates:
              application/json: |
                #set($item = $input.path('$.Item'))
                #set($url = $item.data.M.url.S)
                #if($url != "")
                #set($context.responseOverride.header.X-Terraform-Get = $url)
                #{else}
                #set($context.responseOverride.status = 404)
                {"errors":["Not Found"]}
                #end

  /webhooks/github:
    post:
      parameters:
        - name: X-GitHub-Event
          in: header
        - name: X-GitHub-Delivery
          in: header
        - name: X-Hub-Signature
          in: header
        - name: X-Hub-Signature-256
          in: header
        - name: User-Agent
          in: header

      responses:
        "202":
          description: ""
      x-amazon-apigateway-integration:
        type: mock
        httpMethod: POST
        # type: AWS
        # uri: arn:aws:apigateway:${AWS::Region}:events:action/PutEvents
        # credentials:  arn:${AWS::Partition}:iam::${AWS::AccountId}:role/WebHookRole
        requestTemplates:
          application/json: >-
            {"statusCode": 202}
        responses:
          202:
            statusCode: 202
            responseTemplates:
              application/json: >-
                Hi
