openapi: 3.0.3
info:
  title: Private Terraform Registry
  version: 0.0.1
paths:
  /.well-known/terraform.json:
    get:
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  modules.v1:
                    type: string

  # /{namespace}/{name}/{system}/versions:
  #   get:
  #     x-amazon-apigateway-integration:
  #       httpMethod: POST
  #       type: AWS
  #       uri:
  #         Fn::Sub: "arn:${AWS::Partition}:apigateway:${AWS::Region}:dynamodb:action/GetItem"
  #       credentials:
  #         Fn::GetAtt:
  #           - Role
  #           - Arn
  #       requestTemplates:
  #         application/json:
  #           Fn::Sub:
  #             - |-
  #               {
  #                 "TableName": "${tableName}",
  #                 "Item": {
  #                   "pk": {
  #                     "S": "$context.namespace $context.name $context.system"
  #                   },
  #                   "sk": {
  #                     "S": startswith("VERSION")
  #                   }
  #                 }
  #               }
  #             - { tableName: { Ref: DB } }
  #     responses:
  #       "200":
  #         description: ""
  #         content:
  #           application/json:
  #             schema:
  #               properties:
  #                 modules:
  #                   type: array
  #                   items:
  #                     type: object
  #                     properties:
  #                       versions:
  #                         type: array
  #                         items:
  #                           type: object
  #                           properties:
  #                             version:
  #                               type: string

  # /{namespace}/{name}/{system}/{version}/download:
  #   get:
  #     x-amazon-apigateway-integration:
  #       httpMethod: POST
  #       type: AWS
  #       uri:
  #         Fn::Sub: "arn:${AWS::Partition}:apigateway:${AWS::Region}:dynamodb:action/GetItem"
  #       credentials:
  #         Fn::GetAtt:
  #           - Role
  #           - Arn
  #       requestTemplates:
  #         application/json:
  #           Fn::Sub:
  #             - |-
  #               {
  #                 "TableName": "${tableName}",
  #                 "Item": {
  #                   "pk": {
  #                     "S": "$input.path($.namespace) $context.name $context.system"
  #                   },
  #                   "sk": {
  #                     "S": "VERSION $context.version"
  #                   }
  #                 }
  #               }
  #             - { tableName: { Ref: DB } }
  #     responses:
  #       description: ""
  #       headers:
  #         X-Terraform-Get:
  #           schema:
  #             type: string
