Transform: AWS::Serverless-2016-10-31

Resources:
  Storage:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: TFRegistry

  DB:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Name
          Value: TFRegistry

  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: main
      Variables:
        DB: !Ref DB
      DefinitionBody:
        "Fn::Transform":
          Name: AWS::Include
          Parameters:
            Location: openapi.yaml
      Tags:
        Name: TFRegistry

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub apigateway.${AWS::URLSuffix}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DBRead
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: dynamodb:GetItem
                Resource: !GetAtt DB.Arn
      Tags:
        - Key: Name
          Value: TFRegistry
